sudo: false

language: java

# Get latest install-jdk.sh script
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

env:
  global:
  # taken first download mirror from http://maven.apache.org/
    - BASEURL=http://mirror.softaculous.com/apache/maven/maven-3/VERSION/binaries/apache-maven-VERSION-bin.tar.gz
    - FILE=apache-maven-VERSION-bin.tar.gz
    - DIR=apache-maven-VERSION/bin

matrix:
  include:
    - jdk: openjdk8
      env: MAVEN=3.2.5
    
    - jdk: openjdk9
      env: MAVEN=3.5.4
    
    - jdk: openjdk10
      env: MAVEN=3.5.4
    
    - jdk: openjdk11
      env: MAVEN=3.5.4

    - jdk: openjdk12
      env: MAVEN=3.5.4

    - env: JDK='OpenJ9 11' MAVEN=3.5.4
      install: . ./install-jdk.sh --url "https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=openj9&os=linux&arch=x64&release=latest&type=jdk&heap_size=normal"

  # Java 12 build fails
  allow_failures:
    - jdk: openjdk12
      env: MAVEN=3.5.4

script:
  - wget $(echo -n $BASEURL | sed -e 's#VERSION#'$MAVEN'#g')
  - tar -xvzf $(echo -n $FILE | sed -e 's#VERSION#'$MAVEN'#')
  - export PATH=$(echo -n $DIR | sed -e 's#VERSION#'$MAVEN'#'):$PATH
  - java -version
  - mvn -version
  - mvn clean install 
